export const ACTIONS = {
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SET_GAME_ID: 'SET_GAME_ID',
  RESET_GAME_ID: 'RESET_GAME_ID',
  SET_RED_TEAM_COMMANDER: 'SET_RED_TEAM_COMMANDER',
  SET_BLUE_TEAM_COMMANDER: 'SET_BLUE_TEAM_COMMANDER',
  SET_PLAYER_USER_NAME: 'SET_PLAYER_USER_NAME'
}
