export const ACTIONS = {
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SET_GAME_IN_PROGRESS_TRUE: 'SET_GAME_IN_PROGRESS_TRUE',
  SET_GAME_IN_PROGRESS_FALSE: 'SET_GAME_IN_PROGRESS_FALSE',
  SET_GAME_ID: 'SET_GAME_ID',
  RESET_GAME_ID: 'RESET_GAME_ID',
  SET_RED_PLAYER: 'SET_RED_PLAYER',
  SET_BLUE_PLAYER: 'SET_BLUE_PLAYER',
  INCREMENT_TURN: 'INCREMENT_TURN',
  RESET_GAME_STATE: 'RESET_GAME_STATE'
}
